# Site settings
title: Kotahi - Less Paperwork, better services
email:
description: Ask once then, sharing information

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://kotahi.co" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot:
data-ad-client:
google_ad_client:

google_analytics: ""
addthis_id:
disqus_account: jeky-new-age

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/accreditron
  - title: facebook
    url: https://facebook.com/accreditron
  - title: medium
    url: https://
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
# Build settings
